// <auto-generated />
using System;
using ClearWork.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClearWork.Infrastructure.Migrations
{
    [DbContext(typeof(ClearWorkDbContext))]
    [Migration("20260119170551_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClearWork.Domain.Entities.AnnualTaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<decimal>("DisabilityRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.015m);

                    b.Property<decimal>("HealthRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.09m);

                    b.Property<decimal>("HigherTaxRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.32m);

                    b.Property<decimal>("LowerTaxRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.12m);

                    b.Property<decimal>("PensionRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.0976m);

                    b.Property<decimal>("SicknessRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasDefaultValue(0.0245m);

                    b.Property<decimal>("StandardTaxDeductionMonthly")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(250m);

                    b.Property<decimal>("TaxFreeAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(30000m);

                    b.Property<decimal>("TaxThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(120000m);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<decimal>("YoungPersonTaxReliefLimit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(85528m);

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year")
                        .IsUnique();

                    b.ToTable("AnnualTaxRates");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppThemeSameAsSystem")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("DarkModeDisableTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("DarkModeEnableTime")
                        .HasColumnType("time");

                    b.Property<bool>("DarkModeEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushNotificationEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("PushNotificationReminderTime")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.BusinessTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccommodationType")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<decimal?>("ActualTransportCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("CarEngineCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("EmploymentContractId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("KilometersDriven")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<bool>("UseLocalTransportAllowance")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentContractId");

                    b.ToTable("BusinessTrips");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.EmploymentContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("EmploymentLevel")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("PaymentDay")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("EmploymentContracts");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.Paycheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("EmploymentContractId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentContractId");

                    b.ToTable("Paychecks");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<int>("EmploymentContractId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TextNote")
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentContractId");

                    b.ToTable("TimeEntries");

                    b.HasDiscriminator<string>("EntryType").HasValue("TimeEntry");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.TimeEntryCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppliedTaxDeductionType")
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("ContractTypeUsed")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<decimal>("DisabilityContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("HealthContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PensionContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PpkEmployeeContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PpkEmployerContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SicknessContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("StudentExemptionApplied")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TimeEntryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalZusContributions")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("YoungPersonReliefApplied")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryId")
                        .IsUnique();

                    b.ToTable("TimeEntryCalculations");

                    b.HasDiscriminator<string>("CalculationType").HasValue("TimeEntryCalculation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisabilityLevel")
                        .HasColumnType("varchar");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.LeaveEntry", b =>
                {
                    b.HasBaseType("ClearWork.Domain.Entities.TimeEntry");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Leave");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.WorkEntry", b =>
                {
                    b.HasBaseType("ClearWork.Domain.Entities.TimeEntry");

                    b.Property<int?>("BusinessTripId")
                        .HasColumnType("integer");

                    b.HasIndex("BusinessTripId");

                    b.HasDiscriminator().HasValue("Work");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.LeaveEntryCalculation", b =>
                {
                    b.HasBaseType("ClearWork.Domain.Entities.TimeEntryCalculation");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsPaidBySocialSecurity")
                        .HasColumnType("boolean");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Leave");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.WorkEntryCalculation", b =>
                {
                    b.HasBaseType("ClearWork.Domain.Entities.TimeEntryCalculation");

                    b.Property<decimal>("HourlyRateUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasDiscriminator().HasValue("Work");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.AnnualTaxRate", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.User", "User")
                        .WithMany("AnnualTaxRate")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.AppSetting", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.User", "User")
                        .WithOne("AppSetting")
                        .HasForeignKey("ClearWork.Domain.Entities.AppSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.BusinessTrip", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.EmploymentContract", "EmploymentContract")
                        .WithMany("BusinessTrips")
                        .HasForeignKey("EmploymentContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmploymentContract");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.EmploymentContract", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.Workplace", "Workplace")
                        .WithMany("EmploymentContracts")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.Paycheck", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.EmploymentContract", "EmploymentContract")
                        .WithMany("Paychecks")
                        .HasForeignKey("EmploymentContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmploymentContract");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.EmploymentContract", "EmploymentContract")
                        .WithMany("TimeEntries")
                        .HasForeignKey("EmploymentContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ClearWork.Domain.OwnedTypes.AudioNote", "AudioNote", b1 =>
                        {
                            b1.Property<int>("TimeEntryId")
                                .HasColumnType("integer");

                            b1.Property<byte[]>("AudioData")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<float>("DurationSeconds")
                                .HasColumnType("real");

                            b1.Property<string>("FileFormat")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("m4a");

                            b1.Property<DateTimeOffset>("RecordedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                            b1.HasKey("TimeEntryId");

                            b1.ToTable("TimeEntries");

                            b1.WithOwner()
                                .HasForeignKey("TimeEntryId");
                        });

                    b.Navigation("AudioNote");

                    b.Navigation("EmploymentContract");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.TimeEntryCalculation", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.TimeEntry", "TimeEntry")
                        .WithOne("Calculation")
                        .HasForeignKey("ClearWork.Domain.Entities.TimeEntryCalculation", "TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.Workplace", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.User", "User")
                        .WithMany("Workplaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ClearWork.Domain.OwnedTypes.PpkSetting", "PpkSettings", b1 =>
                        {
                            b1.Property<int>("WorkplaceId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("EmployeeRate")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.02m);

                            b1.Property<decimal>("EmployerRate")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasDefaultValue(0.015m);

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.HasKey("WorkplaceId");

                            b1.ToTable("Workplaces");

                            b1.WithOwner()
                                .HasForeignKey("WorkplaceId");
                        });

                    b.Navigation("PpkSettings");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.WorkEntry", b =>
                {
                    b.HasOne("ClearWork.Domain.Entities.BusinessTrip", "BusinessTrip")
                        .WithMany("WorkEntries")
                        .HasForeignKey("BusinessTripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("ClearWork.Domain.OwnedTypes.DailyBusinessTripDetail", "DailyBusinessTripDetail", b1 =>
                        {
                            b1.Property<int>("WorkEntryId")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("ActualAccommodationCostThisDay")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<bool>("HasOvernightStay")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ProvidedBreakfast")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ProvidedDinner")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ProvidedLunch")
                                .HasColumnType("boolean");

                            b1.HasKey("WorkEntryId");

                            b1.ToTable("TimeEntries");

                            b1.WithOwner()
                                .HasForeignKey("WorkEntryId");
                        });

                    b.Navigation("BusinessTrip");

                    b.Navigation("DailyBusinessTripDetail");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.BusinessTrip", b =>
                {
                    b.Navigation("WorkEntries");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.EmploymentContract", b =>
                {
                    b.Navigation("BusinessTrips");

                    b.Navigation("Paychecks");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.TimeEntry", b =>
                {
                    b.Navigation("Calculation")
                        .IsRequired();
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.User", b =>
                {
                    b.Navigation("AnnualTaxRate");

                    b.Navigation("AppSetting")
                        .IsRequired();

                    b.Navigation("Workplaces");
                });

            modelBuilder.Entity("ClearWork.Domain.Entities.Workplace", b =>
                {
                    b.Navigation("EmploymentContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
